### ISSUE TITLE
Collision at MessageBodyUnpacker?

### ISSUE THREAD

**Issue by araobp** [o3project/odenos#114]
"bodyValue" in getBody method is null when the following line is being processed:

```
body = msgpack.convert(bodyValue, clazz);
```

So IOException is thrown. Has another thread modified "bodyValue"?

```
2015-05-19 17:36:44,716 ERROR MessageBodyUnpacker getBody - IOException
java.io.EOFException
        at org.msgpack.unpacker.Converter.nextValue(Converter.java:49)
        at org.msgpack.unpacker.Converter.ensureValue(Converter.java:54)
        at org.msgpack.unpacker.Converter.trySkipNil(Converter.java:73)
        at org.msgpack.template.MessagePackableTemplate.read(MessagePackableTemplate.java:47)
        at org.msgpack.template.MessagePackableTemplate.read(MessagePackableTemplate.java:26)
        at org.msgpack.template.AbstractTemplate.read(AbstractTemplate.java:31)
        at org.msgpack.MessagePack.convert(MessagePack.java:540)
        at org.o3project.odenos.remoteobject.message.MessageBodyUnpacker.getBody(MessageBodyUnpacker.java:155)
        at org.o3project.odenos.core.component.Logic.onEvent(Logic.java:393)
        at org.o3project.odenos.remoteobject.RemoteObject.doPostEvent(RemoteObject.java:415)
        at org.o3project.odenos.remoteobject.RemoteObject.dispatchEvent(RemoteObject.java:288)
        at org.o3project.odenos.remoteobject.actor.Actor$1.run(Actor.java:181)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by araobp** [comment]
Pending issue.

The error might have been caused by some system-internal error...

**Comment by araobp** [comment]
This is a bug. See #120.
