### ISSUE TITLE
Install failure on Windows

### ISSUE THREAD

**Issue by Evgeny-R** [o3project/odenos#162]
When building latest development version test fails with the following reason:

Running org.o3project.odenos.remoteobject.rest.servlet.RestServletTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.096 sec <<< FAILURE! - in org.o3project.odenos.remoteobject.rest.servlet.RestServletTest
testServiceHttpServletRequestHttpServletResponse(org.o3project.odenos.remoteobject.rest.servlet.RestServletTest)  Time elapsed: 0.017 sec  <<< ERROR!
java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: /\/C:/Users/myuser/Desktop/New%20folder/odenos-develop/target/classes/org/o3project/odenos/remoteobject/rest/servlet/RestServlet.class
    at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
    at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
    at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
    at java.nio.file.Paths.get(Paths.java:84)
    at org.o3project.odenos.remoteobject.rest.servlet.RestServlet.service(RestServlet.java:89)
    at org.o3project.odenos.remoteobject.rest.servlet.RestServletTest.testServiceHttpServletRequestHttpServletResponse(RestServletTest.java:124)

**Comment by haizawa** [comment]
ODENOS not supported for windows.
Please set up in ubuntu14.04.
